In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.cluster import KMeans

In [5]:
nba = "2014-stats.csv"

In [6]:
df_nba = pd.read_csv('2014-stats.csv')

In [7]:
nba = pd.read_csv('2014-stats.csv')

In [8]:
nba

year           player pos  age   tm   g  gs    mp   fg   fga  ...  orb  \
0    2014     Aaron Brooks  PG   29  TOT  72  12  1557  233   581  ...   43   
1    2014       Aaron Gray   C   29  TOT  37   6   355   27    61  ...   42   
2    2014     Andre Miller  SG   37  TOT  58   2   982  106   231  ...   28   
3    2014     Andrew Bynum   C   26  TOT  26  19   516   94   225  ...   53   
4    2014    Arinze Onuaku  PF   26  TOT   5   0    30    1     5  ...    2   
..    ...              ...  ..  ...  ...  ..  ..   ...  ...   ...  ...  ...   
387  2014     Willie Green  SG   32  LAC  55   9   869  102   271  ...   12   
388  2014  Wilson Chandler  SF   26  DEN  62  55  1927  307   738  ...   58   
389  2014     Xavier Henry  SF   22  LAL  43   5   908  144   345  ...   25   
390  2014    Zach Randolph  PF   32  MEM  79  79  2705  560  1198  ...  265   
391  2014    Zaza Pachulia   C   29  MIL  53  43  1325  149   349  ...  141   

     drb  trb  ast  stl  blk  tov   pf   pts  allstar  
0     97  140  233   52   13  117  146   645        0  
1     69  111   22   10    8   31   64    65        0  
2    102  130  197   34    9   61   75   283        0  
3     92  145   29    6   29   34   31   225        0  
4      6    8    3    0    0    1    3     3        0  
..   ...  ...  ...  ...  ...  ...  ...   ...      ...  
387   66   78   50   22   11   34   96   273        0  
388  236  294  114   46   31   79  193   846        0  
389   89  114   51   44    7   57   79   432        0  
390  530  795  200   54   23  183  210  1372        0  
391  192  333  136   45   14   92  124   408        0  

[392 rows x 31 columns]

In [9]:
nba.loc[:, ].mean()

year       2014.000000
age          26.637755
g            53.971939
gs           26.436224
mp         1252.604592
fg          195.466837
fga         428.732143
fgx           0.437335
3p           40.311224
3pa         111.308673
3px           0.284210
2p          155.155612
2pa         317.423469
2px           0.467579
efgx          0.482169
ft           92.910714
fta         122.538265
ftx           0.728232
orb          56.795918
drb         166.783163
trb         223.579082
ast         113.829082
stl          39.964286
blk          25.140306
tov          72.431122
pf          107.107143
pts         524.155612
allstar       0.058673
dtype: float64

In [10]:
kmeans_model = KMeans(n_clusters=5, random_state=1)
clean_model = nba._get_numeric_data().dropna(axis=1)
kmeans_model.fit(clean_model)
name = kmeans_model.labels_
name

array([0, 1, 4, 1, 1, 1, 1, 0, 4, 4, 0, 0, 4, 1, 1, 4, 1, 4, 0, 4, 1, 1,
       4, 0, 1, 1, 0, 0, 4, 1, 4, 4, 1, 4, 4, 2, 1, 1, 1, 1, 0, 4, 2, 4,
       1, 3, 1, 1, 2, 0, 4, 1, 1, 1, 4, 3, 0, 2, 1, 4, 4, 0, 1, 4, 2, 0,
       2, 0, 1, 0, 4, 0, 4, 1, 1, 4, 3, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 1,
       4, 3, 0, 2, 2, 1, 2, 2, 1, 0, 4, 4, 1, 2, 3, 1, 2, 2, 4, 1, 0, 1,
       2, 1, 4, 4, 4, 2, 1, 1, 2, 4, 3, 1, 1, 0, 0, 1, 4, 4, 2, 2, 2, 1,
       4, 3, 3, 2, 4, 4, 2, 1, 4, 1, 4, 1, 3, 4, 4, 0, 1, 1, 2, 4, 1, 0,
       2, 0, 2, 1, 0, 0, 0, 4, 1, 2, 2, 2, 0, 1, 1, 3, 2, 4, 3, 1, 1, 1,
       2, 1, 1, 4, 0, 1, 0, 0, 4, 4, 1, 2, 2, 2, 3, 4, 1, 1, 0, 2, 1, 1,
       1, 4, 3, 4, 0, 2, 4, 2, 2, 2, 2, 4, 0, 1, 1, 4, 4, 4, 0, 1, 2, 1,
       1, 2, 1, 4, 0, 1, 0, 0, 4, 2, 0, 1, 3, 4, 3, 2, 4, 2, 0, 1, 0, 0,
       2, 3, 4, 3, 3, 1, 1, 1, 3, 1, 0, 1, 1, 0, 2, 2, 0, 0, 0, 2, 4, 0,
       4, 4, 0, 1, 1, 4, 2, 0, 2, 2, 1, 1, 0, 1, 0, 0, 1, 3, 1, 4, 1, 1,
       0, 4, 4, 2, 0, 0, 0, 1, 4, 4, 1, 4, 0, 0, 2,

In [11]:
name1 = pd.DataFrame(name)
name1 = name1.rename(columns={0: "clusters"})
name2 = name1['clusters']

In [12]:
name2

0      0
1      1
2      4
3      1
4      1
      ..
387    4
388    0
389    4
390    3
391    4
Name: clusters, Length: 392, dtype: int32

In [12]:
clean_model['clusters'] = name2
clean_model

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  drb  trb  ast  \
0    2014   29  72  12  1557  233   581   96  248  137  ...   97  140  233   
1    2014   29  37   6   355   27    61    0    1   27  ...   69  111   22   
2    2014   37  58   2   982  106   231   11   21   95  ...  102  130  197   
3    2014   26  26  19   516   94   225    0    0   94  ...   92  145   29   
4    2014   26   5   0    30    1     5    0    0    1  ...    6    8    3   
..    ...  ...  ..  ..   ...  ...   ...  ...  ...  ...  ...  ...  ...  ...   
387  2014   32  55   9   869  102   271   41  121   61  ...   66   78   50   
388  2014   26  62  55  1927  307   738  122  351  185  ...  236  294  114   
389  2014   22  43   5   908  144   345   28   81  116  ...   89  114   51   
390  2014   32  79  79  2705  560  1198    2   20  558  ...  530  795  200   
391  2014   29  53  43  1325  149   349    0    1  149  ...  192  333  136   

     stl  blk  tov   pf   pts  allstar  clusters  
0     52   13  117  146   645        0         0  
1     10    8   31   64    65        0         1  
2     34    9   61   75   283        0         4  
3      6   29   34   31   225        0         1  
4      0    0    1    3     3        0         1  
..   ...  ...  ...  ...   ...      ...       ...  
387   22   11   34   96   273        0         4  
388   46   31   79  193   846        0         0  
389   44    7   57   79   432        0         4  
390   54   23  183  210  1372        0         3  
391   45   14   92  124   408        0         4  

[392 rows x 24 columns]

In [13]:
Caron_Butler = clean_model.loc[nba['player'] == 'Caron Butler',: ]
Caron_Butler

year  age   g  gs    mp   fg  fga  3p  3pa   2p  ...  drb  trb  ast  stl  \
7  2014   33  56  13  1419  213  540  98  249  115  ...  208  229   82   47   

   blk  tov   pf  pts  allstar  clusters  
7   17   60  120  587        0         0  

[1 rows x 24 columns]

In [14]:
Caron_Butler_cluster = Caron_Butler.values.tolist()

kmeans_model.predict(Caron_Butler_cluster)

ValueError: Incorrect number of features. Got 24 features, expected 23

In [174]:
Robert_Sacre = clean_model.loc[nba['player'] == 'Robert Sacre',: ]
Robert_Sacre

year  age   g  gs    mp   fg  fga  3p  3pa   2p  ...  drb  trb  ast  stl  \
323  2014   24  65  13  1089  143  300   0    0  143  ...  172  254   51   24   

     blk  tov   pf  pts  allstar  clusters  
323   47   44  134  350        0         4  

[1 rows x 24 columns]

In [175]:
Robert_Sacre_cluster = Robert_Sacre.values.tolist()
kmeans_model.predict(Robert_Sacre_cluster)

ValueError: Incorrect number of features. Got 24 features, expected 23

In [176]:
Andrew_Bynum = clean_model.loc[nba['player'] == 'Andrew Bynum',: ]
Andrew_Bynum
Andrew_Bynum_cluster = Andrew_Bynum.values.tolist()
kmeans_model.predict(Andrew_Bynum_cluster)

ValueError: Incorrect number of features. Got 24 features, expected 23

In [16]:
LeBron_James = clean_model.loc[nba['player'] == 'LeBron James',: ]
LeBron_James

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  drb  trb  ast  \
250  2014   29  77  77  2902  767  1353  116  306  651  ...  452  533  488   

     stl  blk  tov   pf   pts  allstar  clusters  
250  121   26  270  126  2089        1         3  

[1 rows x 24 columns]

In [138]:
LeBron_James_cluster = LeBron_James.values.tolist()
kmeans_model.predict(LeBron_James_cluster)

array([3])

In [139]:
Kevin_Durant = clean_model.loc[nba['player'] == 'Kevin Durant',: ]
Kevin_Durant

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
232  2014   25  81  81  3122  849  1688  192  491  657  ...   58  540  598   

     ast  stl  blk  tov   pf   pts  allstar  
232  445  103   59  285  174  2593        1  

[1 rows x 23 columns]

In [140]:
Kevin_Durant_cluster = Kevin_Durant.values.tolist()
kmeans_model.predict(Kevin_Durant_cluster)

array([3])

In [141]:
Tim_Duncan = clean_model.loc[nba['player'] == 'Tim Duncan',: ]
Tim_Duncan

year  age   g  gs    mp   fg  fga  3p  3pa   2p  ...  orb  drb  trb  ast  \
359  2014   37  74  74  2158  444  906   0    5  444  ...  158  563  721  220   

     stl  blk  tov   pf   pts  allstar  
359   43  139  159  134  1119        0  

[1 rows x 23 columns]

In [142]:
Tim_Duncan_cluster = Tim_Duncan.values.tolist()
kmeans_model.predict(Tim_Duncan_cluster)

array([2])

In [143]:
Kawhi_Leonard = clean_model.loc[nba['player'] == 'Kawhi Leonard',: ]
Kawhi_Leonard

year  age   g  gs    mp   fg  fga  3p  3pa   2p  ...  orb  drb  trb  ast  \
224  2014   22  66  65  1923  337  645  69  182  268  ...   76  336  412  133   

     stl  blk  tov   pf  pts  allstar  
224  114   50   80  127  844        0  

[1 rows x 23 columns]

In [144]:
Kawhi_Leonard_cluster = Kawhi_Leonard.values.tolist()
kmeans_model.predict(Kawhi_Leonard_cluster)

array([0])

In [145]:
Carmelo_Anthony = clean_model.loc[nba['player'] == 'Carmelo Anthony',: ]
Carmelo_Anthony

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
102  2014   29  77  77  2982  743  1643  167  415  576  ...  145  477  622   

     ast  stl  blk  tov   pf   pts  allstar  
102  242   95   51  198  224  2112        1  

[1 rows x 23 columns]

In [146]:
Carmelo_Anthony_cluster = Carmelo_Anthony.values.tolist()
kmeans_model.predict(Carmelo_Anthony_cluster)

array([3])

In [149]:
Stephen_Curry = clean_model.loc[nba['player'] == 'Stephen Curry',: ]
Stephen_Curry

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
348  2014   25  78  78  2846  652  1383  261  615  391  ...   46  288  334   

     ast  stl  blk  tov   pf   pts  allstar  
348  666  128   14  294  194  1873        1  

[1 rows x 23 columns]

In [150]:
Stephen_Curry_cluster = Stephen_Curry.values.tolist()
kmeans_model.predict(Stephen_Curry_cluster)

array([3])

In [151]:
Wesley_Matthews = clean_model.loc[nba['player'] == 'Wesley Matthews',: ]
Wesley_Matthews

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
384  2014   27  82  82  2780  445  1009  201  511  244  ...   51  238  289   

     ast  stl  blk  tov   pf   pts  allstar  
384  197   76   14  110  176  1343        0  

[1 rows x 23 columns]

In [152]:
Wesley_Matthews_cluster = Wesley_Matthews.values.tolist()
kmeans_model.predict(Wesley_Matthews_cluster)

array([2])

In [154]:
Paul_George = clean_model.loc[nba['player'] == 'Paul George',: ]
Paul_George

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
301  2014   23  80  80  2898  577  1362  182  500  395  ...   64  478  542   

     ast  stl  blk  tov   pf   pts  allstar  
301  283  151   22  224  198  1737        1  

[1 rows x 23 columns]

In [155]:
Paul_George_cluster = Paul_George.values.tolist()
kmeans_model.predict(Paul_George_cluster)

array([3])

In [156]:
Danny_Granger = clean_model.loc[nba['player'] == 'Danny Granger',: ]
Danny_Granger

year  age   g  gs   mp   fg  fga  3p  3pa  2p  ...  orb  drb  trb  ast  \
12  2014   30  41   2  847  116  307  43  128  73  ...   31  102  133   41   

    stl  blk  tov  pf  pts  allstar  
12   12   17   46  62  338        0  

[1 rows x 23 columns]

In [157]:
Danny_Granger_cluster = Danny_Granger.values.tolist()
kmeans_model.predict(Danny_Granger_cluster)

array([4])

In [15]:
clean_model.to_csv("clean_model_2014.csv", index=False, header=True)